# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLoR4mbHwwqyqCbkyw2t_q69EOGYMNkN
"""

# STEP 1: Install required packages
!pip install -q fastapi uvicorn nest-asyncio pyngrok tensorflow scikit-learn

# STEP 2: Apply async patch and import libraries
import nest_asyncio
nest_asyncio.apply()

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
from google.colab import files

# STEP 3: Upload your model
uploaded = files.upload()  # Upload your 'tsx_lstm_model.h5' file
model = load_model("tsx_lstm_model.h5")

# STEP 4: Set up FastAPI
app = FastAPI()
scaler = MinMaxScaler(feature_range=(0, 1))

# Root endpoint (avoids 404 on GET /)
@app.get("/")
def read_root():
    return {"message": "Welcome to the stock price prediction API!"}

# Request model
class PriceInput(BaseModel):
    prices: list

# Prediction endpoint
@app.post("/predict")
def predict_next_price(data: PriceInput):
    if len(data.prices) != 60:
        raise HTTPException(status_code=400, detail="Exactly 60 prices are required.")

    try:
        input_prices = np.array(data.prices).reshape(-1, 1)
        scaled_input = scaler.fit_transform(input_prices)
        X_input = scaled_input.reshape(1, 60, 1)
        prediction_scaled = model.predict(X_input)
        prediction = scaler.inverse_transform(prediction_scaled)
        return {"predicted_price": float(prediction[0][0])}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# STEP 5: Set your ngrok authtoken (only once per Colab session)
!ngrok config add-authtoken 2vcYE8JnoOkLB1Lu8YPWnn13K6T_7QwHFLyU9U67C6tVTeLUR

# STEP 6: Launch FastAPI app with ngrok (Colab-safe threading version)
from pyngrok import ngrok
import uvicorn
import threading

# Start ngrok tunnel
public_url = ngrok.connect(8000)
print(f"🚀 FastAPI public URL: {public_url}/docs")

# Launch the FastAPI app in a background thread
def start_uvicorn():
    uvicorn.run(app, host="0.0.0.0", port=8000)

thread = threading.Thread(target=start_uvicorn)
thread.start()