# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yjIMi-FagmF7cheoCj1tNQ-CzrOSy5Zz
"""

# STEP 1: Install Dependencies
!pip install -q numpy pandas matplotlib scikit-learn tensorflow

# STEP 2: Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
import os

# STEP 3: Upload the CSV
from google.colab import files
uploaded = files.upload()

# STEP 4: Load the Data
df = pd.read_csv('tsx_data.csv')
df.head()

# STEP 5: Prepare Data (Using Close Prices)
data = df[['Close']].values  # use Close column only
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)

# Create training sequences
def create_dataset(data, time_step=60):
    X, y = [], []
    for i in range(time_step, len(data)):
        X.append(data[i-time_step:i, 0])
        y.append(data[i, 0])
    return np.array(X), np.array(y)

time_step = 60
X, y = create_dataset(scaled_data, time_step)

# Reshape input to be [samples, time steps, features] for LSTM
X = X.reshape(X.shape[0], X.shape[1], 1)

# STEP 6: Split into Train/Test
split = int(len(X) * 0.8)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# STEP 7: Build LSTM Model
model = Sequential()
model.add(LSTM(50, return_sequences=True, input_shape=(X.shape[1], 1)))
model.add(Dropout(0.2))
model.add(LSTM(50))
model.add(Dropout(0.2))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mean_squared_error')
model.summary()

# STEP 8: Train the Model
history = model.fit(X_train, y_train, epochs=5, batch_size=32, validation_data=(X_test, y_test), verbose=1)

# STEP 9: Evaluate & Predict
predicted = model.predict(X_test)
predicted = scaler.inverse_transform(predicted.reshape(-1, 1))
actual = scaler.inverse_transform(y_test.reshape(-1, 1))

# Plot the results
plt.figure(figsize=(12,6))
plt.plot(actual, color='blue', label='Actual TSX Price')
plt.plot(predicted, color='red', label='Predicted TSX Price')
plt.title('TSX Price Prediction')
plt.xlabel('Time')
plt.ylabel('Price')
plt.legend()
plt.show()

# STEP 10: Save the Model
model.save('tsx_lstm_model.h5')
print("Model saved as 'tsx_lstm_model.h5'")

# Download the model if needed
files.download('tsx_lstm_model.h5')